import { ConditionalType, SizedContainerType } from "./dat-container";

const SCHEMA_WEAPONGRP_DAT: ISchemaValue[] = [
    { type: "uint32", name: "tag" },
    { type: "uint32", name: "id" },
    { type: "uint32", name: "drop_type" },
    { type: "uint32", name: "drop_anim_type" },
    { type: "uint32", name: "drop_radius" },
    { type: "uint32", name: "drop_height" },
    { type: "uint32", name: "UNK_0" },
    { type: "utf16", name: "drop_mesh1" },
    { type: "utf16", name: "drop_mesh2" },
    { type: "utf16", name: "drop_mesh3" },
    { type: "utf16", name: "drop_tex1" },
    { type: "utf16", name: "drop_tex2" },
    { type: "utf16", name: "drop_tex3" },
    { type: new SizedContainerType("utf16", 5), name: "icon" },
    { type: "int32", name: "durability" },
    { type: "uint32", name: "weight" },
    { type: "uint32", name: "material" },
    { type: "uint32", name: "crystallizable" },
    { type: "uint32", name: "projectile_?" },
    { type: "uint32", name: "body_part" },
    { type: "uint32", name: "handness" },
    { type: "uint32", name: "wpn_mesh_cnt" },
    { type: new SizedContainerType("utf16", "wpn_mesh_cnt"), name: "wpn_mesh" },
    { type: "uint32", name: "wpn_tex_cnt" },
    { type: new SizedContainerType("utf16", "wpn_tex_cnt"), name: "wpn_tex" },
    { type: "uint32", name: "item_sound_cnt" },
    { type: new SizedContainerType("utf16", "item_sound_cnt"), name: "item_sound" },
    { type: "utf16", name: "drop_sound" },
    { type: "utf16", name: "equip_sound" },
    { type: "utf16", name: "effect" },
    { type: "uint32", name: "random_damage" },
    { type: "uint32", name: "patt" },
    { type: "uint32", name: "matt" },
    { type: "uint32", name: "weapon_type" },
    { type: "uint32", name: "crystal_type" },
    { type: "uint32", name: "critical" },
    { type: "int32", name: "hit_mod" },
    { type: "int32", name: "avoid_mod" },
    { type: "uint32", name: "shield_pdef" },
    { type: "uint32", name: "shield_rate" },
    { type: "uint32", name: "speed" },
    { type: "uint32", name: "mp_consume" },
    { type: "uint32", name: "SS_count" },
    { type: "uint32", name: "SPS_count" },
    { type: "uint32", name: "curvature" },
    { type: "uint32", name: "UNK_2" },
    { type: "int32", name: "is_hero" },
    { type: "uint32", name: "UNK_3" },
    { type: "utf16", name: "effA" },
    { type: new ConditionalType("utf16", "wpn_mesh_cnt", 2), name: "effB" },
    { type: new SizedContainerType("float", 5), name: "junk1A" },
    { type: new ConditionalType(new SizedContainerType("float", 5), "wpn_mesh_cnt", 2), name: "junk1B" },
    { type: "utf16", name: "rangeA" },
    { type: new ConditionalType("utf16", "wpn_mesh_cnt", 2), name: "rangeB" },
    { type: new SizedContainerType("float", 6), name: "junk2A" },
    { type: new ConditionalType(new SizedContainerType("float", 6), "wpn_mesh_cnt", 2), name: "junk2B" }
];

export default SCHEMA_WEAPONGRP_DAT;
export { SCHEMA_WEAPONGRP_DAT };
