import type { ISchemaValue } from "./dat-schema";
import { SizedContainerType } from "./dat-container";

export const SCHEMA_WEAPONGRP_DAT: ISchemaValue[] = [
    { type: "uint32", name: "tag" },
    { type: "uint32", name: "id" },
    { type: "uint32", name: "drop_type" },
    { type: "uint32", name: "drop_anim_type" },
    { type: "uint32", name: "drop_radius" },
    { type: "uint32", name: "drop_height" },
    { type: "uint32", name: "UNK_0" },
    { type: "utf16", name: "drop_mesh1" },
    { type: "utf16", name: "drop_mesh2" },
    { type: "utf16", name: "drop_mesh3" },
    { type: "utf16", name: "drop_tex1" },
    { type: "utf16", name: "drop_tex2" },
    { type: "utf16", name: "drop_tex3" },
    { type: new SizedContainerType("utf16", 5), name: "icon" },
    { type: "int32", name: "durability" },
    { type: "uint32", name: "weight" },
    { type: "uint32", name: "material" },
    { type: "uint32", name: "crystallizable" },
    { type: "uint32", name: "projectile_?" },
    { type: "uint32", name: "body_part" },
    { type: "uint32", name: "handness" },
    { type: "uint32", name: "wpn_mesh_cnt" },
    { type: new SizedContainerType("utf16", "wpn_mesh_cnt"), name: "wpn_mesh" },
    { type: "uint32", name: "wpn_tex_cnt" },
    { type: new SizedContainerType("utf16", "wpn_tex_cnt"), name: "wpn_tex" },
    { type: "uint32", name: "item_sound_cnt" },
    { type: new SizedContainerType("utf16", "item_sound_cnt"), name: "item_sound" },
    { type: "utf16", name: "drop_sound" },
    { type: "utf16", name: "equip_sound" },
    { type: "utf16", name: "effect" },
    { type: "uint32", name: "random_damage" },
    { type: "uint32", name: "patt" },
    { type: "uint32", name: "matt" },
    { type: "uint32", name: "weapon_type" },
    { type: "uint32", name: "crystal_type" },
    { type: "uint32", name: "critical" },
    { type: "int32", name: "hit_mod" },
    { type: "int32", name: "avoid_mod" },
    { type: "uint32", name: "shield_pdef" },
    { type: "uint32", name: "shield_rate" },
    { type: "uint32", name: "speed" },
    { type: "uint32", name: "mp_consume" },
    { type: "uint32", name: "SS_count" },
    { type: "uint32", name: "SPS_count" },
    { type: "uint32", name: "curvature" },
    { type: "uint32", name: "add_bone" },
    { type: "int32", name: "is_hero" },
    { type: "uint32", name: "UNK_3" },
    { type: new SizedContainerType("utf16", "wpn_mesh_cnt"), name: "enchantedEffect" },
    { type: new SizedContainerType(new SizedContainerType("float", 3), "wpn_mesh_cnt"), name: "enchantedEffectOffset" },
    { type: new SizedContainerType("float", "wpn_mesh_cnt"), name: "enchantedEffectScale" },
    { type: new SizedContainerType("float", "wpn_mesh_cnt"), name: "enchantedEffectVelocityScale" },
    { type: new SizedContainerType("utf16", "wpn_mesh_cnt"), name: "enchantedMesh" },
    { type: new SizedContainerType(new SizedContainerType("float", 3), "wpn_mesh_cnt"), name: "enchantedMeshScale" },
    { type: new SizedContainerType(new SizedContainerType("float", 3), "wpn_mesh_cnt"), name: "enchantedMeshOffset" }
];

export default SCHEMA_WEAPONGRP_DAT;
