type MobSkillTableEntry_T = { name: string, passive?: boolean, target?: "self" | "aura" };

// Server skill metadata; generic target and passive fields only. Pulled from Lisvus.
const mobSkillTable = new Map<number, MobSkillTableEntry_T>([
    [122, { name: "Hex" }],
    [325, { name: "Strider Siege Assault" }],
    [327, { name: "Wyvern Aegis", target: "self" }],
    [1013, { name: "Recharge" }],
    [1044, { name: "Regeneration" }],
    [1045, { name: "Bless the Body" }],
    [1048, { name: "Bless the Soul" }],
    [1059, { name: "Greater Empower" }],
    [1078, { name: "Concentration" }],
    [1085, { name: "Acumen" }],
    [1086, { name: "Haste" }],
    [1160, { name: "Slow" }],
    [1204, { name: "Wind Walk" }],
    [1206, { name: "Wind Shackle" }],
    [1217, { name: "Greater Heal" }],
    [1240, { name: "Guidance" }],
    [1263, { name: "Curse Gloom" }],
    [1268, { name: "Vampiric Rage" }],
    [4001, { name: "NPC Wind Strike" }],
    [4002, { name: "NPC HP Drain" }],
    [4017, { name: "Brandish Queen Ant", target: "aura" }],
    [4018, { name: "Decrease Speed" }],
    [4019, { name: "Decrease Speed" }],
    [4020, { name: "Heal Queen Ant 1" }],
    [4024, { name: "Heal Queen Ant 2" }],
    [4025, { name: "Master Recharge" }],
    [4028, { name: "Enhance P.Atk", target: "self" }],
    [4029, { name: "Enhance P.Def", target: "self" }],
    [4030, { name: "Enhance P.Atk", target: "self" }],
    [4031, { name: "Enhance P.Def", target: "self" }],
    [4032, { name: "NPC Strike" }],
    [4033, { name: "NPC Burn", target: "aura" }],
    [4034, { name: "Decrease Speed" }],
    [4035, { name: "Poison" }],
    [4036, { name: "Poison" }],
    [4037, { name: "Weaken P.Atk" }],
    [4038, { name: "Decrease Atk.Spd." }],
    [4039, { name: "NPC MP Drain" }],
    [4040, { name: "NPC Bow Attack" }],
    [4042, { name: "Nurka Blaze" }],
    [4046, { name: "Sleep" }],
    [4047, { name: "Hold" }],
    [4063, { name: "Paralysis" }],
    [4064, { name: "Paralysis" }],
    [4065, { name: "NPC Heal", target: "self" }],
    [4066, { name: "NPC Twister" }],
    [4067, { name: "NPC Mortal Blow" }],
    [4068, { name: "Mechanical Cannon" }],
    [4069, { name: "NPC Curve Beam Cannon" }],
    [4072, { name: "Shock", target: "aura" }],
    [4073, { name: "Shock" }],
    [4074, { name: "NPC Haste", target: "self" }],
    [4075, { name: "Shock" }],
    [4076, { name: "Reduction in movement speed" }],
    [4077, { name: "NPC Aura Burn" }],
    [4078, { name: "NPC Flamestrike" }],
    [4079, { name: "Siege Hammer" }],
    [4087, { name: "NPC Blaze" }],
    [4088, { name: "Bleed" }],
    [4089, { name: "NPC Bear Stun", target: "self" }],
    [4090, { name: "NPC Wolf Stun", target: "self" }],
    [4091, { name: "NPC Ogre Stun", target: "self" }],
    [4092, { name: "NPC Puma Stun", target: "self" }],
    [4094, { name: "NPC Cancel Magic" }],
    [4096, { name: "NPC Hawkeye", target: "self" }],
    [4097, { name: "NPC Chant of Life", target: "self" }],
    [4098, { name: "Magic Skill Block" }],
    [4099, { name: "NPC Berserk", target: "self" }],
    [4100, { name: "NPC Prominence" }],
    [4101, { name: "NPC Spinning Slasher", target: "aura" }],
    [4102, { name: "Become weak against line of fire" }],
    [4103, { name: "NPC Ultimate Evasion", target: "self" }],
    [4104, { name: "Flame" }],
    [4105, { name: "NPC Straight Beam Cannon" }],
    [4106, { name: "Shock", target: "aura" }],
    [4107, { name: "Shock", target: "aura" }],
    [4108, { name: "Terror" }],
    [4109, { name: "Curse of Antharas", target: "aura" }],
    [4110, { name: "Mouth Odor Attack" }],
    [4111, { name: "Fossilization" }],
    [4112, { name: "Ordinary Attack" }],
    [4113, { name: "Animal doing ordinary attack" }],
    [4117, { name: "Paralysis" }],
    [4118, { name: "Paralysis" }],
    [4119, { name: "Fall in accuracy" }],
    [4120, { name: "Shock" }],
    [4123, { name: "Hostile Feeling" }],
    [4124, { name: "NPC Spear Attack" }],
    [4127, { name: "Baium: General Attack" }],
    [4128, { name: "Wind Of Force", target: "aura" }],
    [4129, { name: "Earthquake", target: "aura" }],
    [4130, { name: "Striking of Thunderbolt" }],
    [4131, { name: "Shock" }],
    [4132, { name: "Spear: Pound the Ground", target: "aura" }],
    [4137, { name: "Hydro Screw" }],
    [4138, { name: "NPC AE - Corpse Burst" }],
    [4140, { name: "Contract Payment" }],
    [4141, { name: "NPC Wind Fist" }],
    [4142, { name: "NPC Fast Wind Fist" }],
    [4151, { name: "NPC Windstrike - Magic" }],
    [4152, { name: "NPC HP Drain - Magic" }],
    [4153, { name: "Decrease Speed" }],
    [4154, { name: "NPC MP Drain - Magic" }],
    [4155, { name: "NPC Twister - Magic" }],
    [4156, { name: "NPC Curve Beam Cannon - Magic" }],
    [4157, { name: "NPC Blaze - Magic" }],
    [4158, { name: "NPC Prominence - Magic" }],
    [4159, { name: "NPC Straight Beam Cannon - Magic" }],
    [4160, { name: "NPC Aura Burn - Magic" }],
    [4161, { name: "Summon PC" }],
    [4163, { name: "NPC Self Damage Shield", target: "self" }],
    [4168, { name: "BOSS Power Strike" }],
    [4169, { name: "Shock" }],
    [4170, { name: "BOSS Mortal Blow" }],
    [4171, { name: "BOSS Spinning Slasher", target: "aura" }],
    [4172, { name: "Shock", target: "aura" }],
    [4173, { name: "BOSS Might", target: "self" }],
    [4174, { name: "BOSS Shield", target: "self" }],
    [4175, { name: "BOSS Haste", target: "self" }],
    [4176, { name: "BOSS Reflect Damage", target: "self" }],
    [4177, { name: "BOSS Cancel Magic", target: "aura" }],
    [4178, { name: "BOSS Flame Strike" }],
    [4179, { name: "BOSS Power Strike" }],
    [4180, { name: "Shock" }],
    [4181, { name: "BOSS Mortal Blow" }],
    [4182, { name: "Poison", target: "aura" }],
    [4183, { name: "Decrease P. Atk.", target: "aura" }],
    [4184, { name: "Decrease Atk. Spd.", target: "aura" }],
    [4185, { name: "Sleep", target: "aura" }],
    [4186, { name: "Hold", target: "aura" }],
    [4187, { name: "Decrease Speed", target: "aura" }],
    [4188, { name: "Bleed", target: "aura" }],
    [4189, { name: "Paralysis", target: "aura" }],
    [4190, { name: "Decrease MP", target: "aura" }],
    [4191, { name: "BOSS Wind Strike" }],
    [4192, { name: "BOSS HP Drain" }],
    [4193, { name: "BOSS Life Drain" }],
    [4194, { name: "BOSS Aura Burn" }],
    [4195, { name: "BOSS Twister" }],
    [4196, { name: "Decreases Speed" }],
    [4197, { name: "Hold" }],
    [4198, { name: "Poison" }],
    [4199, { name: "Decrease P. Atk." }],
    [4200, { name: "Decrease Atk. Spd." }],
    [4201, { name: "Sleep" }],
    [4202, { name: "Hold" }],
    [4203, { name: "Decrease Speed" }],
    [4204, { name: "Bleed" }],
    [4205, { name: "Paralysis" }],
    [4206, { name: "Decrease MP" }],
    [4207, { name: "BOSS Power Shot" }],
    [4208, { name: "Shock" }],
    [4209, { name: "BOSS Heal" }],
    [4210, { name: "Life Chant" }],
    [4211, { name: "BOSS Might" }],
    [4212, { name: "BOSS Shield" }],
    [4213, { name: "BOSS Haste" }],
    [4214, { name: "BOSS Reflect Damage" }],
    [4216, { name: "Scatter Enemy" }],
    [4217, { name: "None" }],
    [4218, { name: "Absorb HP MP", target: "aura" }],
    [4219, { name: "Hold" }],
    [4220, { name: "Deadly Two-Sword Weapon" }],
    [4221, { name: "Deadly Two-Sword Weapon: Range Attack", target: "aura" }],
    [4222, { name: "Instant Move", target: "self" }],
    [4228, { name: "Double Dagger Attack" }],
    [4229, { name: "NPC Double Wind Fist" }],
    [4230, { name: "Wild Cannon" }],
    [4232, { name: "NPC AE Strike" }],
    [4235, { name: "none", passive: true }],
    [4236, { name: "Decrease Heal" }],
    [4237, { name: "Decreases Speed" }],
    [4238, { name: "Increase Re-use Time" }],
    [4244, { name: "NPC Wild Sweep" }],
    [4247, { name: "NPC Windstrike - Slow" }],
    [4248, { name: "NPC HP Drain - Slow" }],
    [4249, { name: "Decrease Speed" }],
    [4250, { name: "NPC Twister - Slow" }],
    [4252, { name: "NPC Flame - Slow" }],
    [4253, { name: "NPC Blaze - Slow" }],
    [4254, { name: "NPC Prominence - Slow" }],
    [4257, { name: "NPC Hydroblast - Magic" }],
    [4259, { name: "Toxic Smoke" }],
    [4260, { name: "Steal Blood" }],
    [4261, { name: "Mega Storm Strike" }],
    [4289, { name: "Wyvern Breath" }],
    [4314, { name: "BOSS Holy Light Burst" }],
    [4315, { name: "Hold" }],
    [4316, { name: "Boss Lilim Drain" }],
    [4317, { name: "Increase Rage Might", target: "self" }],
    [4377, { name: "Wield Temper" }],
    [4378, { name: "Self Damage Shield", target: "self" }],
    [4495, { name: "BOSS Power Shot" }],
    [4496, { name: "Shock" }],
    [4516, { name: "Orfen Heal" }],
    [4523, { name: "Quest - BOSS Evasion" }],
    [4524, { name: "Quest - BOSS Bluff" }],
    [4530, { name: "Quest - Summoned HP Heal" }],
    [4531, { name: "Quest - Summoned MP Heal" }],
    [4533, { name: "Dance of Resist" }],
    [4534, { name: "Dance of Nihil" }],
    [4535, { name: "Dance of Weakness" }],
    [4536, { name: "Song of Seduce" }],
    [4537, { name: "Song of Sweet Whisper" }],
    [4538, { name: "Song of Temptation" }],
    [4539, { name: "Curse of Vague" }],
    [4540, { name: "Curse of Weakness" }],
    [4541, { name: "Curse of Nihil" }],
    [4560, { name: "NPC Fire Burn" }],
    [4561, { name: "NPC Fire Burn - Magic" }],
    [4562, { name: "NPC Solar Flare" }],
    [4563, { name: "NPC Solar Flare - Magic" }],
    [4564, { name: "NPC Solar Flare - Slow" }],
    [4565, { name: "NPC Eruption" }],
    [4566, { name: "NPC Eruption - Magic" }],
    [4567, { name: "NPC Eruption - Slow" }],
    [4568, { name: "NPC AE Solar Flare" }],
    [4569, { name: "NPC AE Solar Flare - Magic" }],
    [4570, { name: "NPC AE Solar Flare - Slow" }],
    [4571, { name: "NPC Blazing Circle", target: "aura" }],
    [4572, { name: "NPC Triple Sonic Slash" }],
    [4573, { name: "NPC Sonic Blaster" }],
    [4574, { name: "NPC Sonic Storm" }],
    [4575, { name: "NPC Clan Buff - Haste" }],
    [4576, { name: "NPC Clan Buff - Damage Shield" }],
    [4577, { name: "Decrease Accuracy" }],
    [4579, { name: "Bleed" }],
    [4580, { name: "Decrease P.Atk" }],
    [4581, { name: "Hold" }],
    [4582, { name: "Poison" }],
    [4584, { name: "Reducing P.Def Shock" }],
    [4585, { name: "NPC Clan Buff - Berserk Might" }],
    [4586, { name: "Decrease Evasion" }],
    [4587, { name: "Decrease P.Atk" }],
    [4588, { name: "NPC Clan Buff - Berserk Haste" }],
    [4589, { name: "Decrease Speed" }],
    [4590, { name: "Decrease Speed" }],
    [4591, { name: "Decrease Speed" }],
    [4592, { name: "Decrease P.Def" }],
    [4593, { name: "Decrease P.Def" }],
    [4594, { name: "Decrease P.Def" }],
    [4595, { name: "NPC Clan Buff - Acumen Shield" }],
    [4596, { name: "Bleed" }],
    [4597, { name: "Bleed" }],
    [4599, { name: "Decrease Speed" }],
    [4600, { name: "Reducing P.Def Shock" }],
    [4601, { name: "NPC Clan Buff - Acumen Focus" }],
    [4603, { name: "Decrease P.Atk" }],
    [4605, { name: "Fire Weakness" }],
    [4606, { name: "Poison" }],
    [4607, { name: "Magma Attack" }],
    [4609, { name: "NPC Clan Buff - Vampiric Rage" }],
    [4613, { name: "NPC Clan Heal" }],
    [4614, { name: "NPC Death Bomb", target: "aura" }],
    [4618, { name: "NPC Cancel PC Target" }],
    [4621, { name: "NPC AE - 80% HP Drain" }],
    [4622, { name: "NPC AE - 80% HP Drain - Magic" }],
    [4628, { name: "Mysterious Aura", target: "self" }],
    [4630, { name: "NPC MR - Twister" }],
    [4631, { name: "NPC Buff - Acumen Shield WildMagic", target: "self" }],
    [4632, { name: "NPC Buff - Acumen Empower WildMagic", target: "self" }],
    [4633, { name: "NPC Buff - Acumen Empower Berserk", target: "self" }],
    [4634, { name: "NPC Buff - Acumen Empower DamageShield", target: "self" }],
    [4635, { name: "NPC Buff - Acumen Berserk WildMagic", target: "self" }],
    [4636, { name: "NPC Buff - Acumen Berserk DamageShield", target: "self" }],
    [4637, { name: "NPC Buff - Acumen WildMagic DamageShield", target: "self" }],
    [4638, { name: "NPC Clan Buff - Acumen Empower WildMagic" }],
    [4639, { name: "NPC Clan Buff - Acumen Empower Berserk" }],
    [4640, { name: "Sleep" }],
    [4641, { name: "NPC Super Strike" }],
    [4643, { name: "Decrease Speed" }],
    [4649, { name: "Poison", target: "aura" }],
    [4650, { name: "NPC AE - Dispel Hold", target: "self" }],
    [4651, { name: "NPC AE - Dispel Slow", target: "self" }],
    [4652, { name: "NPC AE Dispel Silence", target: "self" }],
    [4654, { name: "NPC Death Link" }],
    [4657, { name: "Hold" }],
    [4658, { name: "Hold" }],
    [4663, { name: "NPC Hate" }],
    [4664, { name: "NPC 100% HP Drain" }],
    [4665, { name: "NPC 100% HP Drain - Magic" }],
    [4671, { name: "AV - Teleport" }],
    [4675, { name: "NPC Dispel Fighter Buff" }],
    [4680, { name: "Valakas Lava Skin", target: "self" }],
    [4681, { name: "Valakas Trample", target: "aura" }],
    [4682, { name: "Valakas Trample", target: "aura" }],
    [4683, { name: "Valakas Dragon Breath", target: "aura" }],
    [4684, { name: "Valakas Dragon Breath", target: "aura" }],
    [4685, { name: "Valakas Tail Stomp", target: "aura" }],
    [4687, { name: "Valakas Tail Stomp", target: "self" }],
    [4688, { name: "Valakas Shock", target: "aura" }],
    [4689, { name: "Valakas Fear" }],
    [4690, { name: "Valakas Meteor Storm", target: "aura" }],
    [4692, { name: "Quest BOSS Big Body", target: "self" }],
    [4693, { name: "Quest BOSS Dispel Big Body", target: "self" }],
    [4694, { name: "Ultimate Debuff" }],
    [4695, { name: "Ultimate Debuff" }],
    [4696, { name: "Ultimate Debuff" }],
    [4697, { name: "NPC Monster Hate", target: "aura" }],
    [4699, { name: "Blessing of Queen" }],
    [4700, { name: "Gift of Queen" }],
    [4701, { name: "Cure of Queen" }],
    [4702, { name: "Blessing of Seraphim" }],
    [4703, { name: "Gift of Seraphim" }],
    [4704, { name: "Cure of Seraphim" }],
    [4705, { name: "Curse of Shade" }],
    [4706, { name: "Mass Curse of Shade", target: "aura" }],
    [4707, { name: "Shade Sacrifice" }],
    [4708, { name: "Cursed Strike" }],
    [4709, { name: "Cursed Blow" }],
    [4710, { name: "Wild Stun" }],
    [4711, { name: "Wild Defense", target: "self" }],
    [4712, { name: "Bright Burst" }],
    [4713, { name: "Bright Heal" }],
    [4717, { name: "Heal Trick" }],
    [4718, { name: "Greater Heal Trick" }],
    [4719, { name: "BOSS Strike" }],
    [4720, { name: "BOSS Strike" }],
    [4721, { name: "BOSS Strike" }],
    [4722, { name: "BOSS Strike" }],
    [4723, { name: "BOSS Strike" }],
    [4724, { name: "Shock" }],
    [4725, { name: "Shock" }],
    [4726, { name: "Shock" }],
    [4727, { name: "Shock" }],
    [4728, { name: "Shock" }],
    [4729, { name: "BOSS Mortal Blow" }],
    [4730, { name: "BOSS Mortal Blow" }],
    [4731, { name: "BOSS Mortal Blow" }],
    [4732, { name: "BOSS Mortal Blow" }],
    [4733, { name: "BOSS Mortal Blow" }],
    [4734, { name: "BOSS Spinning Slasher" }],
    [4735, { name: "BOSS Spinning Slasher" }],
    [4736, { name: "BOSS Spinning Slasher" }],
    [4737, { name: "BOSS Spinning Slasher" }],
    [4738, { name: "BOSS Spinning Slasher" }],
    [4739, { name: "BOSS Strike" }],
    [4740, { name: "BOSS Strike" }],
    [4741, { name: "BOSS Strike" }],
    [4742, { name: "BOSS Strike" }],
    [4743, { name: "BOSS Strike" }],
    [4744, { name: "Shock" }],
    [4745, { name: "Shock" }],
    [4746, { name: "Shock" }],
    [4748, { name: "Shock" }],
    [4751, { name: "BOSS Mortal Blow" }],
    [4752, { name: "BOSS Mortal Blow" }],
    [4753, { name: "BOSS Mortal Blow" }],
    [4754, { name: "BOSS Power Shot" }],
    [4755, { name: "BOSS Power Shot" }],
    [4756, { name: "BOSS Power Shot" }],
    [4757, { name: "BOSS Power Shot" }],
    [4758, { name: "BOSS Power Shot" }],
    [4759, { name: "Shock" }],
    [4760, { name: "Shock" }],
    [4761, { name: "Shock" }],
    [4774, { name: "BOSS Spear Attack" }],
    [4777, { name: "BOSS Spear Attack" }],
    [4778, { name: "BOSS Spear Attack" }],
    [4779, { name: "BOSS Heal" }],
    [4780, { name: "BOSS Heal" }],
    [4781, { name: "BOSS Heal" }],
    [4782, { name: "BOSS Heal" }],
    [4783, { name: "BOSS Heal" }],
    [4784, { name: "BOSS Chant of Life" }],
    [4785, { name: "BOSS Chant of Life" }],
    [4786, { name: "BOSS Chant of Life" }],
    [4788, { name: "BOSS Chant of Life" }],
]);

export default mobSkillTable;
