type MobSkillTableEntry_T = { passive?: boolean, target?: "self" | "aura" };

// Pulled from Lisvus skill XML; tools/generate-mob-skill-table.cjs.
const mobSkillTable = new Map<number, MobSkillTableEntry_T>([
    [4, { target: "self" }],
    [8, { target: "self" }],
    [10, { target: "self" }],
    [13, { target: "self" }],
    [18, { target: "aura" }],
    [21, { target: "self" }],
    [22, { target: "self" }],
    [25, { target: "self" }],
    [33, { target: "self" }],
    [34, { target: "self" }],
    [36, { target: "aura" }],
    [44, { target: "self" }],
    [45, { target: "self" }],
    [48, { target: "aura" }],
    [50, { target: "self" }],
    [58, { target: "self" }],
    [60, { target: "self" }],
    [61, { target: "self" }],
    [67, { target: "self" }],
    [72, { target: "self" }],
    [75, { target: "self" }],
    [76, { target: "self" }],
    [77, { target: "self" }],
    [78, { target: "self" }],
    [80, { target: "self" }],
    [82, { target: "self" }],
    [83, { target: "self" }],
    [84, { target: "aura" }],
    [86, { target: "self" }],
    [87, { target: "self" }],
    [88, { target: "self" }],
    [91, { target: "self" }],
    [94, { target: "self" }],
    [97, { target: "aura" }],
    [98, { target: "aura" }],
    [99, { target: "self" }],
    [104, { target: "self" }],
    [107, { target: "aura" }],
    [109, { target: "self" }],
    [110, { target: "self" }],
    [111, { target: "self" }],
    [112, { target: "self" }],
    [113, { passive: true, target: "self" }],
    [116, { target: "aura" }],
    [118, { passive: true, target: "self" }],
    [121, { target: "self" }],
    [123, { target: "self" }],
    [130, { target: "self" }],
    [131, { target: "self" }],
    [134, { passive: true, target: "self" }],
    [137, { passive: true, target: "self" }],
    [139, { target: "self" }],
    [141, { passive: true, target: "self" }],
    [142, { passive: true, target: "self" }],
    [143, { passive: true, target: "self" }],
    [144, { passive: true, target: "self" }],
    [146, { passive: true, target: "self" }],
    [147, { passive: true, target: "self" }],
    [148, { passive: true, target: "self" }],
    [150, { passive: true, target: "self" }],
    [153, { passive: true, target: "self" }],
    [163, { passive: true, target: "self" }],
    [164, { passive: true, target: "self" }],
    [165, { passive: true, target: "self" }],
    [167, { passive: true, target: "self" }],
    [168, { passive: true, target: "self" }],
    [169, { passive: true, target: "self" }],
    [171, { passive: true, target: "self" }],
    [172, { passive: true, target: "self" }],
    [173, { passive: true, target: "self" }],
    [176, { target: "self" }],
    [181, { target: "self" }],
    [191, { passive: true, target: "self" }],
    [193, { passive: true, target: "self" }],
    [194, { passive: true, target: "self" }],
    [195, { passive: true, target: "self" }],
    [196, { target: "self" }],
    [197, { target: "self" }],
    [198, { passive: true, target: "self" }],
    [205, { passive: true, target: "self" }],
    [208, { passive: true, target: "self" }],
    [209, { passive: true, target: "self" }],
    [210, { passive: true, target: "self" }],
    [211, { passive: true, target: "self" }],
    [212, { passive: true, target: "self" }],
    [213, { passive: true, target: "self" }],
    [214, { passive: true, target: "self" }],
    [216, { passive: true, target: "self" }],
    [217, { passive: true, target: "self" }],
    [221, { target: "self" }],
    [222, { target: "self" }],
    [225, { passive: true, target: "self" }],
    [226, { target: "self" }],
    [227, { passive: true, target: "self" }],
    [228, { passive: true, target: "self" }],
    [229, { passive: true, target: "self" }],
    [230, { target: "self" }],
    [231, { passive: true, target: "self" }],
    [232, { passive: true, target: "self" }],
    [233, { passive: true, target: "self" }],
    [234, { passive: true, target: "self" }],
    [235, { passive: true, target: "self" }],
    [236, { passive: true, target: "self" }],
    [239, { passive: true, target: "self" }],
    [240, { passive: true, target: "self" }],
    [241, { passive: true, target: "self" }],
    [242, { passive: true, target: "self" }],
    [243, { passive: true, target: "self" }],
    [244, { passive: true, target: "self" }],
    [247, { target: "self" }],
    [248, { passive: true, target: "self" }],
    [249, { passive: true, target: "self" }],
    [250, { passive: true, target: "self" }],
    [251, { passive: true, target: "self" }],
    [252, { passive: true, target: "self" }],
    [253, { passive: true, target: "self" }],
    [256, { target: "self" }],
    [257, { passive: true, target: "self" }],
    [258, { passive: true, target: "self" }],
    [259, { passive: true, target: "self" }],
    [278, { target: "self" }],
    [282, { target: "self" }],
    [283, { target: "self" }],
    [285, { passive: true, target: "self" }],
    [286, { target: "aura" }],
    [287, { target: "self" }],
    [288, { target: "self" }],
    [290, { passive: true, target: "self" }],
    [291, { passive: true, target: "self" }],
    [292, { target: "self" }],
    [293, { passive: true, target: "self" }],
    [294, { passive: true, target: "self" }],
    [295, { passive: true, target: "self" }],
    [296, { target: "self" }],
    [297, { target: "self" }],
    [298, { target: "self" }],
    [299, { target: "self" }],
    [301, { target: "self" }],
    [303, { target: "self" }],
    [312, { target: "self" }],
    [313, { target: "self" }],
    [316, { passive: true, target: "self" }],
    [317, { target: "self" }],
    [318, { target: "self" }],
    [319, { passive: true, target: "self" }],
    [322, { target: "self" }],
    [323, { target: "self" }],
    [324, { target: "self" }],
    [326, { target: "self" }],
    [327, { target: "self" }],
    [328, { passive: true, target: "self" }],
    [329, { passive: true, target: "self" }],
    [330, { passive: true, target: "self" }],
    [331, { passive: true, target: "self" }],
    [332, { passive: true }],
    [333, { passive: true }],
    [334, { target: "self" }],
    [335, { target: "self" }],
    [336, { target: "self" }],
    [337, { target: "self" }],
    [338, { target: "self" }],
    [339, { target: "self" }],
    [340, { target: "self" }],
    [347, { target: "aura" }],
    [350, { target: "self" }],
    [351, { target: "self" }],
    [355, { target: "self" }],
    [356, { target: "self" }],
    [357, { target: "self" }],
    [359, { target: "self" }],
    [360, { target: "self" }],
    [367, { target: "aura" }],
    [368, { target: "aura" }],
    [1001, { target: "self" }],
    [1047, { target: "self" }],
    [1049, { target: "aura" }],
    [1050, { target: "self" }],
    [1096, { target: "aura" }],
    [1099, { target: "aura" }],
    [1101, { target: "aura" }],
    [1104, { target: "aura" }],
    [1108, { target: "aura" }],
    [1111, { target: "self" }],
    [1128, { target: "self" }],
    [1157, { target: "self" }],
    [1171, { target: "aura" }],
    [1208, { target: "aura" }],
    [1209, { target: "aura" }],
    [1210, { target: "aura" }],
    [1213, { target: "aura" }],
    [1216, { target: "self" }],
    [1225, { target: "self" }],
    [1226, { target: "self" }],
    [1227, { target: "self" }],
    [1228, { target: "self" }],
    [1246, { target: "aura" }],
    [1247, { target: "aura" }],
    [1248, { target: "aura" }],
    [1262, { target: "self" }],
    [1272, { target: "aura" }],
    [1273, { target: "aura" }],
    [1276, { target: "self" }],
    [1277, { target: "self" }],
    [1278, { target: "self" }],
    [1279, { target: "self" }],
    [1280, { target: "self" }],
    [1281, { target: "self" }],
    [1283, { target: "self" }],
    [1297, { passive: true, target: "self" }],
    [1312, { target: "self" }],
    [1313, { target: "self" }],
    [1314, { target: "self" }],
    [1315, { passive: true, target: "self" }],
    [1320, { passive: true, target: "self" }],
    [1321, { target: "self" }],
    [1322, { target: "self" }],
    [1324, { target: "self" }],
    [1331, { target: "self" }],
    [1332, { target: "self" }],
    [1333, { target: "self" }],
    [1344, { target: "aura" }],
    [1345, { target: "aura" }],
    [1360, { target: "aura" }],
    [1361, { target: "aura" }],
    [1366, { target: "aura" }],
    [1368, { passive: true, target: "self" }],
    [1369, { passive: true, target: "self" }],
    [1370, { passive: true, target: "self" }],
    [1371, { passive: true, target: "self" }],
    [1372, { passive: true, target: "self" }],
    [1373, { passive: true }],
    [2001, { target: "self" }],
    [2002, { target: "self" }],
    [2003, { target: "self" }],
    [2005, { target: "self" }],
    [2010, { target: "self" }],
    [2011, { target: "self" }],
    [2012, { target: "self" }],
    [2013, { target: "self" }],
    [2023, { target: "self" }],
    [2024, { target: "self" }],
    [2025, { target: "self" }],
    [2031, { target: "self" }],
    [2032, { target: "self" }],
    [2033, { target: "self" }],
    [2034, { target: "self" }],
    [2035, { target: "self" }],
    [2036, { target: "self" }],
    [2037, { target: "self" }],
    [2038, { target: "self" }],
    [2039, { target: "self" }],
    [2040, { target: "self" }],
    [2041, { target: "self" }],
    [2042, { target: "self" }],
    [2043, { target: "self" }],
    [2044, { target: "self" }],
    [2045, { target: "self" }],
    [2046, { target: "self" }],
    [2047, { target: "self" }],
    [2048, { target: "self" }],
    [2050, { target: "self" }],
    [2051, { target: "self" }],
    [2052, { target: "self" }],
    [2053, { target: "self" }],
    [2054, { target: "self" }],
    [2055, { target: "self" }],
    [2056, { target: "self" }],
    [2057, { target: "self" }],
    [2058, { target: "self" }],
    [2059, { target: "self" }],
    [2060, { target: "self" }],
    [2061, { target: "self" }],
    [2063, { target: "self" }],
    [2064, { target: "self" }],
    [2066, { target: "self" }],
    [2067, { target: "self" }],
    [2068, { target: "self" }],
    [2069, { target: "self" }],
    [2070, { target: "self" }],
    [2071, { target: "self" }],
    [2072, { target: "self" }],
    [2073, { target: "self" }],
    [2076, { target: "self" }],
    [2099, { target: "self" }],
    [2100, { target: "self" }],
    [2101, { target: "self" }],
    [2102, { target: "self" }],
    [2103, { target: "self" }],
    [2122, { target: "self" }],
    [2123, { target: "self" }],
    [2124, { target: "self" }],
    [2125, { target: "self" }],
    [2126, { target: "self" }],
    [2127, { target: "self" }],
    [2128, { target: "self" }],
    [2129, { target: "self" }],
    [2130, { target: "self" }],
    [2131, { target: "self" }],
    [2132, { target: "self" }],
    [2133, { target: "self" }],
    [2134, { target: "self" }],
    [2135, { target: "self" }],
    [2136, { target: "self" }],
    [2140, { target: "self" }],
    [2141, { target: "self" }],
    [2142, { target: "self" }],
    [2143, { target: "self" }],
    [2144, { target: "self" }],
    [2145, { target: "self" }],
    [2146, { target: "self" }],
    [2147, { target: "self" }],
    [2148, { target: "self" }],
    [2149, { target: "self" }],
    [2150, { target: "self" }],
    [2151, { target: "self" }],
    [2152, { target: "self" }],
    [2153, { target: "self" }],
    [2154, { target: "self" }],
    [2155, { target: "self" }],
    [2156, { target: "self" }],
    [2157, { target: "self" }],
    [2158, { target: "self" }],
    [2159, { target: "self" }],
    [2160, { target: "self" }],
    [2161, { target: "self" }],
    [2162, { target: "self" }],
    [2163, { target: "self" }],
    [2164, { target: "self" }],
    [2165, { target: "self" }],
    [2166, { target: "self" }],
    [2167, { target: "self" }],
    [2168, { target: "self" }],
    [2169, { target: "self" }],
    [2177, { target: "self" }],
    [2178, { target: "self" }],
    [2180, { target: "self" }],
    [2187, { target: "self" }],
    [2213, { target: "self" }],
    [2214, { target: "self" }],
    [2230, { target: "self" }],
    [2231, { target: "self" }],
    [2232, { target: "self" }],
    [2233, { target: "self" }],
    [3001, { passive: true, target: "self" }],
    [3002, { passive: true, target: "self" }],
    [3003, { passive: true, target: "self" }],
    [3004, { passive: true, target: "self" }],
    [3006, { passive: true, target: "self" }],
    [3007, { passive: true, target: "self" }],
    [3008, { passive: true, target: "self" }],
    [3009, { passive: true, target: "self" }],
    [3010, { passive: true, target: "self" }],
    [3011, { passive: true, target: "self" }],
    [3012, { passive: true, target: "self" }],
    [3013, { passive: true, target: "self" }],
    [3014, { passive: true, target: "self" }],
    [3018, { passive: true, target: "self" }],
    [3019, { passive: true, target: "self" }],
    [3023, { passive: true, target: "self" }],
    [3026, { passive: true }],
    [3027, { passive: true, target: "self" }],
    [3028, { passive: true, target: "self" }],
    [3029, { passive: true, target: "self" }],
    [3030, { passive: true, target: "self" }],
    [3031, { passive: true, target: "self" }],
    [3032, { passive: true, target: "self" }],
    [3033, { passive: true, target: "self" }],
    [3034, { passive: true, target: "self" }],
    [3035, { passive: true, target: "self" }],
    [3036, { passive: true, target: "self" }],
    [3037, { passive: true, target: "self" }],
    [3038, { passive: true, target: "self" }],
    [3042, { passive: true, target: "self" }],
    [3043, { passive: true, target: "self" }],
    [3044, { passive: true, target: "self" }],
    [3045, { passive: true, target: "self" }],
    [3046, { passive: true, target: "self" }],
    [3047, { passive: true, target: "self" }],
    [3048, { passive: true, target: "self" }],
    [3049, { passive: true }],
    [3050, { passive: true, target: "self" }],
    [3051, { passive: true, target: "self" }],
    [3056, { passive: true, target: "self" }],
    [3057, { passive: true, target: "self" }],
    [3058, { passive: true, target: "self" }],
    [3063, { passive: true, target: "self" }],
    [3064, { passive: true, target: "self" }],
    [3065, { passive: true, target: "self" }],
    [3066, { passive: true, target: "self" }],
    [3067, { passive: true, target: "self" }],
    [3068, { passive: true, target: "self" }],
    [3069, { passive: true, target: "self" }],
    [3071, { passive: true, target: "self" }],
    [3072, { passive: true, target: "self" }],
    [3073, { passive: true, target: "self" }],
    [3076, { passive: true, target: "self" }],
    [3077, { passive: true, target: "self" }],
    [3500, { passive: true, target: "self" }],
    [3501, { passive: true, target: "self" }],
    [3502, { passive: true, target: "self" }],
    [3503, { passive: true, target: "self" }],
    [3504, { passive: true, target: "self" }],
    [3505, { passive: true, target: "self" }],
    [3506, { passive: true, target: "self" }],
    [3507, { passive: true, target: "self" }],
    [3508, { passive: true, target: "self" }],
    [3509, { passive: true, target: "self" }],
    [3510, { passive: true, target: "self" }],
    [3511, { passive: true, target: "self" }],
    [3512, { passive: true, target: "self" }],
    [3513, { passive: true, target: "self" }],
    [3514, { passive: true, target: "self" }],
    [3515, { passive: true, target: "self" }],
    [3516, { passive: true, target: "self" }],
    [3517, { passive: true, target: "self" }],
    [3518, { passive: true, target: "self" }],
    [3519, { passive: true, target: "self" }],
    [3520, { passive: true, target: "self" }],
    [3521, { passive: true, target: "self" }],
    [3522, { passive: true, target: "self" }],
    [3523, { passive: true, target: "self" }],
    [3524, { passive: true, target: "self" }],
    [3525, { passive: true, target: "self" }],
    [3526, { passive: true, target: "self" }],
    [3527, { passive: true, target: "self" }],
    [3528, { passive: true, target: "self" }],
    [3529, { passive: true, target: "self" }],
    [3530, { passive: true, target: "self" }],
    [3531, { passive: true, target: "self" }],
    [3532, { passive: true, target: "self" }],
    [3533, { passive: true, target: "self" }],
    [3534, { passive: true, target: "self" }],
    [3535, { passive: true, target: "self" }],
    [3536, { passive: true, target: "self" }],
    [3537, { passive: true, target: "self" }],
    [3538, { passive: true, target: "self" }],
    [3539, { passive: true, target: "self" }],
    [3540, { passive: true, target: "self" }],
    [3541, { passive: true, target: "self" }],
    [3542, { passive: true }],
    [3543, { passive: true, target: "self" }],
    [3544, { passive: true, target: "self" }],
    [3545, { passive: true, target: "self" }],
    [3546, { passive: true, target: "self" }],
    [3547, { passive: true, target: "self" }],
    [3548, { passive: true, target: "self" }],
    [3549, { passive: true, target: "self" }],
    [3550, { passive: true, target: "self" }],
    [3551, { passive: true, target: "self" }],
    [3552, { passive: true }],
    [3553, { passive: true, target: "self" }],
    [3554, { passive: true, target: "self" }],
    [3555, { passive: true, target: "self" }],
    [3556, { passive: true, target: "self" }],
    [3557, { passive: true, target: "self" }],
    [3558, { passive: true, target: "self" }],
    [3559, { passive: true, target: "self" }],
    [3560, { passive: true, target: "self" }],
    [3561, { passive: true, target: "self" }],
    [3562, { passive: true, target: "self" }],
    [3563, { passive: true, target: "self" }],
    [3564, { passive: true }],
    [3565, { passive: true }],
    [3566, { passive: true }],
    [3567, { passive: true, target: "self" }],
    [3568, { passive: true }],
    [3569, { passive: true }],
    [3570, { passive: true }],
    [3572, { passive: true }],
    [3573, { passive: true }],
    [3575, { passive: true }],
    [3576, { passive: true }],
    [3578, { passive: true, target: "self" }],
    [3580, { passive: true, target: "self" }],
    [3582, { passive: true, target: "self" }],
    [3583, { passive: true, target: "self" }],
    [3585, { passive: true, target: "self" }],
    [3587, { passive: true, target: "self" }],
    [3589, { passive: true, target: "self" }],
    [3591, { passive: true, target: "self" }],
    [3593, { passive: true, target: "self" }],
    [3595, { passive: true, target: "self" }],
    [3596, { target: "self" }],
    [3597, { passive: true, target: "self" }],
    [3598, { target: "self" }],
    [3599, { passive: true, target: "self" }],
    [3600, { passive: true }],
    [3601, { passive: true }],
    [3602, { passive: true }],
    [4003, { passive: true, target: "self" }],
    [4004, { passive: true, target: "self" }],
    [4005, { passive: true, target: "self" }],
    [4006, { passive: true, target: "self" }],
    [4007, { passive: true, target: "self" }],
    [4008, { passive: true, target: "self" }],
    [4009, { passive: true, target: "self" }],
    [4010, { passive: true, target: "self" }],
    [4011, { passive: true, target: "self" }],
    [4012, { passive: true, target: "self" }],
    [4013, { passive: true, target: "self" }],
    [4014, { passive: true, target: "self" }],
    [4015, { passive: true, target: "self" }],
    [4016, { passive: true, target: "self" }],
    [4017, { target: "aura" }],
    [4021, { passive: true, target: "self" }],
    [4022, { passive: true, target: "self" }],
    [4023, { passive: true, target: "self" }],
    [4028, { target: "self" }],
    [4029, { target: "self" }],
    [4030, { target: "self" }],
    [4031, { target: "self" }],
    [4033, { target: "aura" }],
    [4041, { passive: true, target: "self" }],
    [4043, { passive: true, target: "self" }],
    [4044, { passive: true, target: "self" }],
    [4045, { passive: true, target: "self" }],
    [4048, { target: "self" }],
    [4056, { passive: true, target: "self" }],
    [4057, { passive: true, target: "self" }],
    [4058, { passive: true, target: "self" }],
    [4059, { passive: true, target: "self" }],
    [4060, { passive: true, target: "self" }],
    [4061, { passive: true, target: "self" }],
    [4062, { passive: true, target: "self" }],
    [4065, { target: "self" }],
    [4071, { passive: true, target: "self" }],
    [4072, { target: "aura" }],
    [4074, { target: "self" }],
    [4082, { target: "self" }],
    [4084, { passive: true, target: "self" }],
    [4085, { passive: true, target: "self" }],
    [4086, { passive: true, target: "self" }],
    [4089, { target: "self" }],
    [4090, { target: "self" }],
    [4091, { target: "self" }],
    [4092, { target: "self" }],
    [4093, { passive: true, target: "self" }],
    [4095, { passive: true, target: "self" }],
    [4096, { target: "self" }],
    [4097, { target: "self" }],
    [4099, { target: "self" }],
    [4101, { target: "aura" }],
    [4103, { target: "self" }],
    [4106, { target: "aura" }],
    [4107, { target: "aura" }],
    [4109, { target: "aura" }],
    [4116, { passive: true, target: "self" }],
    [4121, { passive: true, target: "self" }],
    [4122, { passive: true, target: "self" }],
    [4125, { passive: true, target: "self" }],
    [4126, { passive: true, target: "self" }],
    [4128, { target: "aura" }],
    [4129, { target: "aura" }],
    [4132, { target: "aura" }],
    [4133, { passive: true, target: "self" }],
    [4134, { passive: true, target: "self" }],
    [4135, { target: "self" }],
    [4139, { target: "aura" }],
    [4143, { passive: true, target: "self" }],
    [4144, { passive: true, target: "self" }],
    [4145, { passive: true, target: "self" }],
    [4146, { passive: true, target: "self" }],
    [4147, { passive: true, target: "self" }],
    [4148, { passive: true, target: "self" }],
    [4149, { passive: true, target: "self" }],
    [4150, { passive: true, target: "self" }],
    [4162, { passive: true, target: "self" }],
    [4163, { target: "self" }],
    [4167, { passive: true, target: "self" }],
    [4171, { target: "aura" }],
    [4172, { target: "aura" }],
    [4173, { target: "self" }],
    [4174, { target: "self" }],
    [4175, { target: "self" }],
    [4176, { target: "self" }],
    [4177, { target: "aura" }],
    [4182, { target: "aura" }],
    [4183, { target: "aura" }],
    [4184, { target: "aura" }],
    [4185, { target: "aura" }],
    [4186, { target: "aura" }],
    [4187, { target: "aura" }],
    [4188, { target: "aura" }],
    [4189, { target: "aura" }],
    [4190, { target: "aura" }],
    [4218, { target: "aura" }],
    [4221, { target: "aura" }],
    [4222, { target: "self" }],
    [4223, { passive: true, target: "self" }],
    [4224, { passive: true, target: "self" }],
    [4225, { passive: true, target: "self" }],
    [4226, { passive: true, target: "self" }],
    [4227, { target: "self" }],
    [4233, { passive: true, target: "self" }],
    [4234, { passive: true, target: "self" }],
    [4235, { passive: true, target: "self" }],
    [4239, { passive: true, target: "self" }],
    [4240, { passive: true, target: "self" }],
    [4241, { passive: true, target: "self" }],
    [4242, { target: "self" }],
    [4245, { passive: true, target: "self" }],
    [4246, { passive: true, target: "self" }],
    [4256, { passive: true, target: "self" }],
    [4262, { passive: true, target: "self" }],
    [4263, { passive: true, target: "self" }],
    [4264, { passive: true, target: "self" }],
    [4265, { passive: true, target: "self" }],
    [4266, { passive: true, target: "self" }],
    [4267, { passive: true, target: "self" }],
    [4268, { passive: true, target: "self" }],
    [4269, { passive: true, target: "self" }],
    [4270, { passive: true, target: "self" }],
    [4271, { passive: true }],
    [4272, { passive: true, target: "self" }],
    [4273, { passive: true, target: "self" }],
    [4274, { passive: true, target: "self" }],
    [4275, { passive: true, target: "self" }],
    [4276, { passive: true, target: "self" }],
    [4277, { passive: true, target: "self" }],
    [4278, { passive: true }],
    [4279, { passive: true, target: "self" }],
    [4280, { passive: true, target: "self" }],
    [4281, { passive: true, target: "self" }],
    [4282, { passive: true, target: "self" }],
    [4283, { passive: true, target: "self" }],
    [4284, { passive: true, target: "self" }],
    [4285, { passive: true, target: "self" }],
    [4286, { passive: true, target: "self" }],
    [4287, { passive: true, target: "self" }],
    [4288, { passive: true, target: "self" }],
    [4290, { passive: true }],
    [4291, { passive: true }],
    [4292, { passive: true }],
    [4293, { passive: true }],
    [4294, { passive: true }],
    [4295, { passive: true }],
    [4296, { passive: true }],
    [4297, { passive: true }],
    [4298, { passive: true }],
    [4299, { passive: true }],
    [4300, { passive: true }],
    [4301, { passive: true }],
    [4302, { passive: true }],
    [4303, { passive: true, target: "self" }],
    [4304, { passive: true, target: "self" }],
    [4305, { passive: true, target: "self" }],
    [4306, { passive: true, target: "self" }],
    [4307, { passive: true, target: "self" }],
    [4308, { passive: true, target: "self" }],
    [4309, { passive: true, target: "self" }],
    [4310, { passive: true, target: "self" }],
    [4311, { passive: true, target: "self" }],
    [4312, { passive: true, target: "self" }],
    [4313, { passive: true, target: "self" }],
    [4317, { target: "self" }],
    [4318, { target: "self" }],
    [4332, { passive: true, target: "self" }],
    [4333, { passive: true, target: "self" }],
    [4335, { passive: true }],
    [4336, { passive: true, target: "self" }],
    [4337, { passive: true, target: "self" }],
    [4338, { target: "self" }],
    [4340, { target: "self" }],
    [4341, { target: "self" }],
    [4376, { passive: true }],
    [4378, { target: "self" }],
    [4379, { passive: true, target: "self" }],
    [4381, { target: "self" }],
    [4383, { passive: true }],
    [4384, { passive: true }],
    [4385, { passive: true }],
    [4386, { passive: true }],
    [4387, { passive: true }],
    [4388, { passive: true, target: "self" }],
    [4389, { passive: true, target: "self" }],
    [4390, { passive: true }],
    [4494, { passive: true }],
    [4497, { passive: true }],
    [4498, { passive: true }],
    [4499, { passive: true }],
    [4500, { passive: true }],
    [4501, { passive: true }],
    [4502, { passive: true }],
    [4503, { passive: true }],
    [4504, { passive: true }],
    [4505, { passive: true }],
    [4506, { passive: true }],
    [4507, { passive: true }],
    [4508, { passive: true }],
    [4509, { passive: true }],
    [4510, { passive: true }],
    [4511, { passive: true }],
    [4512, { passive: true }],
    [4571, { target: "aura" }],
    [4614, { target: "aura" }],
    [4616, { target: "self" }],
    [4617, { target: "self" }],
    [4626, { target: "self" }],
    [4627, { target: "self" }],
    [4628, { target: "self" }],
    [4631, { target: "self" }],
    [4632, { target: "self" }],
    [4633, { target: "self" }],
    [4634, { target: "self" }],
    [4635, { target: "self" }],
    [4636, { target: "self" }],
    [4637, { target: "self" }],
    [4642, { passive: true, target: "self" }],
    [4649, { target: "aura" }],
    [4650, { target: "self" }],
    [4651, { target: "self" }],
    [4652, { target: "self" }],
    [4672, { target: "self" }],
    [4679, { passive: true, target: "self" }],
    [4680, { target: "self" }],
    [4681, { target: "aura" }],
    [4682, { target: "aura" }],
    [4683, { target: "aura" }],
    [4684, { target: "aura" }],
    [4685, { target: "aura" }],
    [4686, { target: "aura" }],
    [4687, { target: "self" }],
    [4688, { target: "aura" }],
    [4690, { target: "aura" }],
    [4691, { target: "self" }],
    [4692, { target: "self" }],
    [4693, { target: "self" }],
    [4697, { target: "aura" }],
    [4698, { target: "self" }],
    [4706, { target: "aura" }],
    [4711, { target: "self" }],
    [4789, { passive: true, target: "self" }],
    [4800, { passive: true, target: "self" }],
    [4801, { passive: true, target: "self" }],
    [4802, { passive: true, target: "self" }],
    [4803, { passive: true, target: "self" }],
    [4804, { passive: true, target: "self" }],
    [4805, { passive: true, target: "self" }],
    [4806, { passive: true, target: "self" }],
    [4807, { passive: true, target: "self" }],
    [4808, { passive: true, target: "self" }],
    [4809, { passive: true, target: "self" }],
    [4810, { passive: true, target: "self" }],
    [4811, { passive: true, target: "self" }],
    [4812, { passive: true, target: "self" }],
    [4813, { passive: true, target: "self" }],
    [4814, { passive: true, target: "self" }],
    [4815, { passive: true, target: "self" }],
    [4816, { passive: true, target: "self" }],
    [4817, { passive: true, target: "self" }],
    [4818, { passive: true, target: "self" }],
    [4819, { passive: true, target: "self" }],
    [4820, { passive: true, target: "self" }],
    [4821, { passive: true, target: "self" }],
    [4822, { passive: true, target: "self" }],
    [4823, { passive: true, target: "self" }],
    [4824, { passive: true, target: "self" }],
    [4825, { passive: true, target: "self" }],
    [4826, { passive: true, target: "self" }],
    [4827, { passive: true, target: "self" }],
    [4828, { passive: true, target: "self" }],
    [4829, { passive: true, target: "self" }],
    [4830, { passive: true, target: "self" }],
    [4831, { passive: true, target: "self" }],
    [4832, { passive: true, target: "self" }],
    [4833, { passive: true, target: "self" }],
    [4834, { passive: true, target: "self" }],
    [4835, { passive: true, target: "self" }],
    [4836, { passive: true, target: "self" }],
    [4837, { passive: true, target: "self" }],
    [4838, { passive: true, target: "self" }],
    [4839, { passive: true, target: "self" }],
    [4840, { passive: true, target: "self" }],
    [4841, { passive: true, target: "self" }],
    [4842, { passive: true, target: "self" }],
    [4843, { passive: true, target: "self" }],
    [4844, { passive: true, target: "self" }],
    [4845, { passive: true, target: "self" }],
    [4846, { passive: true, target: "self" }],
    [4847, { passive: true, target: "self" }],
    [4848, { passive: true, target: "self" }],
    [4849, { passive: true, target: "self" }],
    [4850, { passive: true, target: "self" }],
    [4851, { passive: true, target: "self" }],
    [4852, { passive: true, target: "self" }],
    [4853, { passive: true, target: "self" }],
    [4854, { passive: true, target: "self" }],
    [4855, { passive: true, target: "self" }],
    [4856, { passive: true, target: "self" }],
    [4857, { passive: true, target: "self" }],
    [4858, { passive: true, target: "self" }],
    [4859, { passive: true, target: "self" }],
    [4860, { passive: true, target: "self" }],
    [4861, { passive: true, target: "self" }],
    [4862, { passive: true, target: "self" }],
    [4863, { passive: true, target: "self" }],
    [4864, { passive: true, target: "self" }],
    [4865, { passive: true, target: "self" }],
    [4866, { passive: true, target: "self" }],
    [4867, { passive: true, target: "self" }],
    [4868, { passive: true, target: "self" }],
    [4869, { passive: true, target: "self" }],
    [4870, { passive: true, target: "self" }],
    [4871, { passive: true, target: "self" }],
    [4872, { passive: true, target: "self" }],
    [4873, { passive: true, target: "self" }],
    [4874, { passive: true, target: "self" }],
    [4875, { passive: true, target: "self" }],
    [4876, { passive: true, target: "self" }],
    [4877, { passive: true, target: "self" }],
    [4878, { passive: true, target: "self" }],
    [4879, { passive: true, target: "self" }],
    [4880, { passive: true, target: "self" }],
    [4881, { passive: true, target: "self" }],
    [4882, { passive: true, target: "self" }],
    [4883, { passive: true, target: "self" }],
    [4884, { passive: true, target: "self" }],
    [4885, { passive: true, target: "self" }],
    [4886, { passive: true, target: "self" }],
    [4887, { passive: true, target: "self" }],
    [4888, { passive: true, target: "self" }],
    [4889, { passive: true, target: "self" }],
    [4890, { passive: true, target: "self" }],
    [4891, { passive: true, target: "self" }],
    [4892, { passive: true, target: "self" }],
    [4893, { passive: true, target: "self" }],
    [4894, { passive: true, target: "self" }],
    [4895, { passive: true, target: "self" }],
    [4896, { passive: true, target: "self" }],
    [4897, { passive: true, target: "self" }],
    [4898, { passive: true, target: "self" }],
    [4899, { passive: true, target: "self" }],
    [4900, { passive: true, target: "self" }],
    [4901, { passive: true, target: "self" }],
    [4902, { passive: true, target: "self" }],
    [4903, { passive: true, target: "self" }],
    [4904, { passive: true, target: "self" }],
    [4905, { passive: true, target: "self" }],
    [4906, { passive: true, target: "self" }],
    [4907, { passive: true, target: "self" }],
    [4908, { passive: true, target: "self" }],
    [4909, { passive: true, target: "self" }],
    [4910, { passive: true, target: "self" }],
    [4911, { passive: true, target: "self" }],
    [4912, { passive: true, target: "self" }],
    [4913, { passive: true, target: "self" }],
    [4914, { passive: true, target: "self" }],
    [4915, { passive: true, target: "self" }],
    [4916, { passive: true, target: "self" }],
    [4917, { passive: true, target: "self" }],
    [4918, { passive: true, target: "self" }],
    [4919, { passive: true, target: "self" }],
    [4920, { passive: true, target: "self" }],
    [4921, { passive: true, target: "self" }],
    [4922, { passive: true, target: "self" }],
    [4923, { passive: true, target: "self" }],
    [4924, { passive: true, target: "self" }],
    [4925, { passive: true, target: "self" }],
    [4926, { passive: true, target: "self" }],
    [4927, { passive: true, target: "self" }],
    [4928, { passive: true, target: "self" }],
    [4929, { passive: true, target: "self" }],
    [4930, { passive: true, target: "self" }],
    [4931, { passive: true, target: "self" }],
    [4932, { passive: true, target: "self" }],
    [4933, { passive: true, target: "self" }],
    [4934, { passive: true, target: "self" }],
    [4935, { passive: true, target: "self" }],
    [4936, { passive: true, target: "self" }],
    [4937, { passive: true, target: "self" }],
    [4938, { passive: true, target: "self" }],
    [4939, { passive: true, target: "self" }],
    [4940, { passive: true, target: "self" }],
    [4941, { passive: true, target: "self" }],
    [4942, { passive: true, target: "self" }],
    [4943, { passive: true, target: "self" }],
    [4944, { passive: true, target: "self" }],
    [4945, { passive: true, target: "self" }],
    [4946, { passive: true, target: "self" }],
    [4947, { passive: true, target: "self" }],
    [4948, { passive: true, target: "self" }],
    [4949, { passive: true, target: "self" }],
    [4950, { passive: true, target: "self" }],
    [4951, { passive: true, target: "self" }],
    [4952, { passive: true, target: "self" }],
    [4953, { passive: true, target: "self" }],
    [4954, { passive: true, target: "self" }],
    [4955, { passive: true, target: "self" }],
    [4956, { passive: true, target: "self" }],
    [4957, { passive: true, target: "self" }],
    [4958, { passive: true, target: "self" }],
    [4959, { passive: true, target: "self" }],
    [4960, { passive: true, target: "self" }],
    [4961, { passive: true, target: "self" }],
    [4962, { passive: true, target: "self" }],
    [4963, { passive: true, target: "self" }],
    [4964, { passive: true, target: "self" }],
    [4965, { passive: true, target: "self" }],
    [4966, { passive: true, target: "self" }],
    [4967, { passive: true, target: "self" }],
    [4968, { passive: true, target: "self" }],
    [4969, { passive: true, target: "self" }],
    [4970, { passive: true, target: "self" }],
    [4971, { passive: true, target: "self" }],
    [4972, { passive: true, target: "self" }],
    [4973, { passive: true, target: "self" }],
    [4974, { passive: true, target: "self" }],
    [4975, { passive: true, target: "self" }],
    [4976, { passive: true, target: "self" }],
    [4977, { passive: true, target: "self" }],
    [4978, { passive: true, target: "self" }],
    [4979, { passive: true, target: "self" }],
    [4980, { passive: true, target: "self" }],
    [4981, { passive: true, target: "self" }],
    [4982, { passive: true, target: "self" }],
    [4983, { passive: true, target: "self" }],
    [4984, { passive: true, target: "self" }],
    [4985, { passive: true, target: "self" }],
    [4986, { passive: true, target: "self" }],
    [4987, { passive: true, target: "self" }],
    [4988, { passive: true, target: "self" }],
    [7003, { passive: true, target: "self" }],
    [7004, { passive: true, target: "self" }],
    [7005, { target: "self" }],
    [7006, { target: "self" }],
    [7007, { target: "self" }],
    [7029, { target: "self" }],
    [7030, { target: "self" }],
    [7031, { target: "self" }],
    [7032, { target: "self" }],
    [9001, { passive: true, target: "self" }],
    [9002, { passive: true, target: "self" }],
    [9003, { passive: true, target: "self" }],
    [9004, { passive: true, target: "self" }],
    [9005, { passive: true, target: "self" }],
    [9006, { passive: true, target: "self" }],
    [9900, { target: "self" }],
]);

export default mobSkillTable;
