// Generated by tools/export-native-skill-dispatch.cjs from the hash-pinned Engine.dll export.
const nativeSkillDispatch = new Map<string, Map<number, string>>([
    ["s_stun_shot_boss_a_", new Map([
        // Init / PreShot / Shot / Explosion: 0x7a18b4 / 0x7a43c0 / 0x7af8cb / 0x7918db.
        [4208, "bossStunShot"],
        // Init / PreShot / Shot / Explosion: 0x7a1220 / 0x7a3de7 / 0x7af576 / 0x7918db.
        [4496, "bossSpearStun"],
    ])],
    ["s_stun_shot_boss_a_1a_1", new Map([
        // Init / PreShot / Shot / Explosion: 0x7a17a8 / 0x7a43c0 / 0x7afa26 / 0x7916c7.
        [4756, "bow"],
        // Init / PreShot / Shot / Explosion: 0x7a18b4 / 0x7a43c0 / 0x7af8cb / 0x7918db.
        [4761, "bossStunShot"],
    ])],
    ["s_npc_hate", new Map([
        // Init / PreShot / Shot / Explosion: 0x79f5c8 / 0x7a3de7 / 0x7b0749 / 0x791ade.
        [4123, "npcHate"],
        // Init / PreShot / Shot / Explosion: 0x79c74b / 0x7a3de7 / 0x7b0e38 / 0x791ade.
        [4663, "empty"],
    ])],
]);

export default nativeSkillDispatch;
