// Generated by tools/export-player-skill-dispatch.cjs; Engine.dll SHA256 fa3f0f2a6a4ad5f6de83f9e7cf1d8c2bb4ad9c8079673975b34e033dd3172c9c.
// Native fallback recipes; serialized SkillVisualEffect takes precedence.
const nativeSkillHandlers = new Map<number, string>();

for (const id of [3, 100, 223, 245, 4032])
    nativeSkillHandlers.set(id, "powerStrike");

for (const id of [4, 8, 75, 80, 86, 87, 88, 99, 104, 130, 131, 230, 297, 4176])
    nativeSkillHandlers.set(id, "dash");

for (const id of [16])
    nativeSkillHandlers.set(id, "mortalBlow");

for (const id of [21, 61, 1012, 1013, 1018, 4025])
    nativeSkillHandlers.set(id, "recharge");

for (const id of [2, 11, 12, 15, 18, 28, 51, 65, 102, 106, 107, 115, 122, 127, 286, 1062, 1064, 1069, 1071, 1072, 1074, 1075, 1083, 1223, 1224, 1273, 4046, 4098, 4099, 4102, 4123, 4185, 4201])
    nativeSkillHandlers.set(id, "sleep");

for (const id of [34, 44, 45, 69, 262, 1011, 1126, 1127, 1216, 4065, 4209])
    nativeSkillHandlers.set(id, "heal");

for (const id of [56, 4040, 4120, 4207, 4754, 4755, 4756, 4757])
    nativeSkillHandlers.set(id, "powerShot");

for (const id of [70])
    nativeSkillHandlers.set(id, "drainHealth");

for (const id of [50, 76, 77, 78, 82, 83, 91, 94, 109, 112, 121, 139, 176, 181, 282, 292, 298, 303, 4028, 4029, 4089, 4090, 4091, 4092, 4096, 4103])
    nativeSkillHandlers.set(id, "warCry");

for (const id of [92, 284, 4072, 4073, 4075, 4220])
    nativeSkillHandlers.set(id, "shieldStun");

for (const id of [101, 4208, 4760, 4761])
    nativeSkillHandlers.set(id, "stunShot");

for (const id of [129, 1156, 1160, 1163, 1168, 1169, 1170, 1263, 1269, 4035, 4076, 4117, 4119, 4198, 4199, 4203, 4205, 4206])
    nativeSkillHandlers.set(id, "poison");

for (const id of [27, 246, 1068, 1078, 1087, 1157, 1182, 1191, 4030, 4074, 4173, 4211])
    nativeSkillHandlers.set(id, "might");

for (const id of [49, 1028, 1031, 1042])
    nativeSkillHandlers.set(id, "disruptUndead");

for (const id of [1032, 1033, 1035, 1036, 1040, 1232, 1238, 1259, 4031, 4163, 4174, 4212])
    nativeSkillHandlers.set(id, "shield");

for (const id of [1043, 1044, 1045, 1047, 1048])
    nativeSkillHandlers.set(id, "regeneration");

for (const id of [1056, 1059, 1073, 1085, 1139, 1140, 1141, 1144, 1145, 1146, 1257, 4094, 4177])
    nativeSkillHandlers.set(id, "empower");

for (const id of [1077, 1086, 1240, 1242, 1268, 4175, 4213, 4214])
    nativeSkillHandlers.set(id, "haste");

for (const id of [10, 13, 22, 25, 33, 67, 247, 278, 283, 299, 301, 1111, 1128, 1129, 1154, 1225, 1226, 1227, 1228, 1276, 1277, 1278, 1279, 1280, 1281])
    nativeSkillHandlers.set(id, "summon");

for (const id of [1090, 1147, 1151, 1234, 1245, 4002, 4039, 4152, 4154, 4192, 4193, 4218, 4248, 4260, 4596, 4597, 4664, 4665])
    nativeSkillHandlers.set(id, "vampiricTouch");

for (const id of [1164, 1222, 4037])
    nativeSkillHandlers.set(id, "curseWeakness");

for (const id of [103, 1167, 1272, 4036, 4118, 4182, 4183, 4187, 4189, 4190, 4259])
    nativeSkillHandlers.set(id, "poisonousCloud");

for (const id of [1172, 1274, 4033, 4077, 4160, 4194])
    nativeSkillHandlers.set(id, "auraBurn");

for (const id of [1177, 4001, 4151, 4191, 4247, 4261])
    nativeSkillHandlers.set(id, "windStrike");

for (const id of [1178, 4066, 4155, 4195, 4250])
    nativeSkillHandlers.set(id, "twister");

for (const id of [1181, 4078, 4178, 4252])
    nativeSkillHandlers.set(id, "flameStrike");

for (const id of [1189, 1204])
    nativeSkillHandlers.set(id, "windWalk");

for (const id of [98, 1201, 1233, 4047, 4186, 4197, 4202, 4219])
    nativeSkillHandlers.set(id, "dryadRoot");

for (const id of [1206, 4038, 4184, 4200])
    nativeSkillHandlers.set(id, "windShackle");

for (const id of [1020, 1217, 1218, 1219, 1258, 1271])
    nativeSkillHandlers.set(id, "greaterHeal");

for (const id of [1220, 1230, 1289, 4042, 4087, 4100, 4157, 4158, 4253, 4254])
    nativeSkillHandlers.set(id, "blaze");

for (const id of [29, 95])
    nativeSkillHandlers.set(id, "ironPunch");

for (const id of [54])
    nativeSkillHandlers.set(id, "forceBlaster");

for (const id of [120, 281, 4063, 4064, 4067, 4168, 4169, 4170, 4171, 4172, 4179, 4180, 4181, 4244])
    nativeSkillHandlers.set(id, "stunningFist");

for (const id of [1002, 1003, 1004, 1007, 1229, 1249, 1251, 1253, 1256, 1282, 1364, 1365, 4097, 4210])
    nativeSkillHandlers.set(id, "chantOfLife");

for (const id of [1005, 1006, 1008, 1009, 1010, 1250, 1252, 1260, 1261, 1284])
    nativeSkillHandlers.set(id, "chantOfShielding");

for (const id of [1016, 1254])
    nativeSkillHandlers.set(id, "resurrection");

for (const id of [1092, 1095, 1096, 1097, 1099, 1102, 1104, 1105, 1208, 1209, 1210, 1213, 1246, 1247, 1248, 1366, 1367, 4238])
    nativeSkillHandlers.set(id, "seal");

for (const id of [1100, 1107, 1244])
    nativeSkillHandlers.set(id, "chillFlame");

for (const id of [1101, 1108, 4104, 4188])
    nativeSkillHandlers.set(id, "blazeQuake");

for (const id of [42, 313, 315, 320, 321, 323, 324, 325, 326, 327, 341, 342, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 355, 356, 357, 358, 359, 360, 361, 363, 364, 365, 366, 367, 368, 1295, 1296, 1298, 1299, 1300, 1301, 1303, 1305, 1306, 1307, 1308, 1309, 1310, 1311, 1312, 1313, 1314, 1321, 1322, 1323, 1324, 1325, 1326, 1327, 1328, 1329, 1330, 1331, 1332, 1333, 1334, 1335, 1336, 1337, 1338, 1339, 1340, 1341, 1342, 1343, 1344, 1345, 1346, 1347, 1348, 1349, 1350, 1351, 1352, 1353, 1354, 1355, 1356, 1357, 1358, 1359, 1360, 1361, 4108, 4140, 4289, 4316, 4317, 4377, 4378, 4516, 4523, 4524, 4530, 4531, 4533, 4534, 4535, 4536, 4537, 4538, 4539, 4540, 4541, 4560, 4561, 4562, 4563, 4564, 4565, 4566, 4567, 4568, 4569, 4570, 4571, 4572, 4573, 4574, 4575, 4576, 4577, 4579, 4580, 4581, 4582, 4584, 4585, 4586, 4587, 4588, 4589, 4590, 4591, 4592, 4593, 4594, 4595, 4599, 4600, 4601, 4603, 4605, 4606, 4607, 4609, 4613, 4614, 4618, 4628, 4630, 4631, 4632, 4634, 4635, 4636, 4637, 4638, 4640, 4641, 4643, 4649, 4650, 4651, 4652, 4654, 4663, 4671, 4675, 4680, 4681, 4682, 4683, 4684, 4685, 4687, 4688, 4692, 4693, 4694, 4695, 4696, 4697, 4699, 4700, 4701, 4702, 4703, 4704, 4705, 4706, 4707, 4708, 4709, 4710, 4711, 4712, 4713, 4717, 4718, 4719, 4720, 4721, 4722, 4723, 4724, 4725, 4726, 4727, 4728, 4729, 4730, 4731, 4732, 4733, 4734, 4735, 4736, 4737, 4738, 4739, 4740, 4741, 4742, 4743, 4744, 4745, 4746, 4748, 4751, 4752, 4753, 4758, 4759, 4774, 4777, 4778, 4779, 4780, 4781, 4782, 4783, 4784, 4785, 4786, 4788])
    nativeSkillHandlers.set(id, "empty");

for (const id of [254, 302])
    nativeSkillHandlers.set(id, "spoil");

for (const id of [72, 110, 111, 123, 287])
    nativeSkillHandlers.set(id, "ultimateDefense");

for (const id of [30, 36, 48, 190, 255, 260])
    nativeSkillHandlers.set(id, "powerSmash");

for (const id of [1])
    nativeSkillHandlers.set(id, "tripleSlash");

for (const id of [5, 261])
    nativeSkillHandlers.set(id, "sonicSlash");

for (const id of [6])
    nativeSkillHandlers.set(id, "sonicBlaster");

for (const id of [7])
    nativeSkillHandlers.set(id, "sonicStorm");

for (const id of [9])
    nativeSkillHandlers.set(id, "sonicBuster");

for (const id of [17, 81])
    nativeSkillHandlers.set(id, "forceBuster");

for (const id of [19])
    nativeSkillHandlers.set(id, "doubleShot");

for (const id of [24])
    nativeSkillHandlers.set(id, "burstShot");

for (const id of [35])
    nativeSkillHandlers.set(id, "forceStorm");

for (const id of [46, 289])
    nativeSkillHandlers.set(id, "lifeScavenge");

for (const id of [84])
    nativeSkillHandlers.set(id, "poisonBladeDance");

for (const id of [97, 116, 1034, 1049])
    nativeSkillHandlers.set(id, "sanctuary");

for (const id of [263])
    nativeSkillHandlers.set(id, "deadlyBlow");

for (const id of [264, 265, 266, 267, 268, 269, 270, 304, 305, 306, 308])
    nativeSkillHandlers.set(id, "song");

for (const id of [271, 272, 273, 274, 275, 276, 277, 307, 309, 310, 311])
    nativeSkillHandlers.set(id, "dance");

for (const id of [279, 1264, 1265])
    nativeSkillHandlers.set(id, "lightningStrike");

for (const id of [280])
    nativeSkillHandlers.set(id, "burningFist");

for (const id of [1050, 4222])
    nativeSkillHandlers.set(id, "return");

for (const id of [1148])
    nativeSkillHandlers.set(id, "deathSpike");

for (const id of [1155, 4138])
    nativeSkillHandlers.set(id, "corpseBurst");

for (const id of [1159, 1266, 1267])
    nativeSkillHandlers.set(id, "curseDeathLink");

for (const id of [1183, 1235, 4137, 4257])
    nativeSkillHandlers.set(id, "hydroBlast");

for (const id of [1239, 1291, 4236])
    nativeSkillHandlers.set(id, "hurricane");

for (const id of [1243, 1304])
    nativeSkillHandlers.set(id, "blessShield");

for (const id of [1255])
    nativeSkillHandlers.set(id, "partyRecall");

for (const id of [1285])
    nativeSkillHandlers.set(id, "seedOfFire");

for (const id of [1287])
    nativeSkillHandlers.set(id, "seedOfWind");

for (const id of [314])
    nativeSkillHandlers.set(id, "fatalCounter");

for (const id of [343, 354])
    nativeSkillHandlers.set(id, "lethalShot");

for (const id of [362])
    nativeSkillHandlers.set(id, "armorCrush");

for (const id of [1362, 1363, 4633, 4639])
    nativeSkillHandlers.set(id, "chantOfSpirit");

for (const id of [369])
    nativeSkillHandlers.set(id, "evadeShot");

for (const id of [4235])
    nativeSkillHandlers.set(id, "devastatedRecall");

export default nativeSkillHandlers;
