const assetList = Object.freeze([
    "maps/17_22.unr",
    "maps/20_19.unr",
    "maps/20_20.unr",
    "maps/20_21.unr",
    "maps/20_22.unr",
    "maps/21_19.unr",
    "maps/21_20.unr",
    "maps/21_21.unr",
    "maps/22_21.unr",
    "textures/T_17_22.utx",
    "textures/T_20_19.utx",
    "textures/T_20_20.utx",
    "textures/T_20_21.utx",
    "textures/T_20_22.utx",
    "textures/T_21_19.utx",
    "textures/T_21_20.utx",
    "textures/T_21_21.utx",
    "textures/T_22_21.utx",
    "textures/L2_Skies.utx",
    "textures/T_sland.utx",
    "textures/T_texture.utx",
    "textures/T_Gludio.utx",
    "textures/Gludio_Tree_T.utx",
    "textures/T_Dion.utx",
    "textures/T_oren.utx",
    "textures/L2DecoLayer.utx",
    "textures/field_deco_T.utx",
    "textures/Dion_tree_T.utx",
    "textures/dion_curumadungeon_t.utx",
    "textures/cruma_tr_t.utx",
    "models/field_deco_S.usx",
    "models/Dion_Cruma_Tower_S.usx",
    "models/Dion_tree_S.usx",
    "models/gludio_tree_S.usx",
    "models/dion_curumadungeon_s.usx",
    "models/dion_curumadungeon_boss_s.usx",
    "models/cruma_s.usx",
    "sounds2/AmbSound.uax",
    "sounds2/ChrSound.uax",
    "engine/Engine.u",
]);

export default assetList;
export { assetList };