const assetList = Object.freeze([
    "maps/Entry.unr",
    "maps/17_22.unr",
    "maps/20_19.unr",
    "maps/20_20.unr",
    "maps/20_21.unr",
    "maps/20_22.unr",
    "maps/21_19.unr",
    "maps/21_20.unr",
    "maps/21_21.unr",
    "maps/22_21.unr",

    "textures/T_SHADER.utx",
    "textures/T_17_22.utx",
    "textures/T_20_19.utx",
    "textures/T_20_20.utx",
    "textures/T_20_21.utx",
    "textures/T_20_22.utx",
    "textures/T_21_19.utx",
    "textures/T_21_20.utx",
    "textures/T_21_21.utx",
    "textures/T_22_21.utx",
    "textures/L2_Skies.utx",
    "textures/Oren_HEV_T.utx",
    "textures/L2_ETC_Textures.utx",
    "textures/T_sland.utx",
    "textures/T_texture.utx",
    "textures/T_Gludio.utx",
    "textures/Gludio_Tree_T.utx",
    "textures/Oren_HED_T2.utx",
    "textures/Dion_NorthVillage_T.utx",
    "textures/Castle_Kent_t.utx",
    "textures/T_Dion.utx",
    "textures/T_oren.utx",
    "textures/L2DecoLayer.utx",
    "textures/field_deco_T.utx",
    "textures/Dion_tree_T.utx",
    "textures/dion_curumadungeon_t.utx",
    "textures/cruma_tr_t.utx",
    "textures/FX_E_T.utx",
    "textures/Oren_tree_T.utx",
    "textures/Oren_HEV_LOD_T.utx",
    "textures/Field_Deco_Artifact_T.utx",

    "staticmeshes/Oren_HED_enterance.usx",
    "staticmeshes/Oren_HED_S.usx",
    "staticmeshes/Field_Deco_Artifact_S.usx",
    "staticmeshes/Oren_HEV_LOD_S.usx",
    "staticmeshes/Oren_HEV_S.usx",
    "staticmeshes/field_deco_S.usx",
    "staticmeshes/Oren_tree_S.usx",
    "staticmeshes/Dion_Cruma_Tower_S.usx",
    "staticmeshes/Dion_tree_S.usx",
    "staticmeshes/gludio_tree_S.usx",
    "staticmeshes/dion_curumadungeon_s.usx",
    "staticmeshes/dion_curumadungeon_boss_s.usx",
    "staticmeshes/cruma_s.usx",

    "sounds/AmbSound.uax",
    "sounds/ChrSound.uax",

    "system/Engine.u",
    "system/Core.u",

    "animations/LineageEffectMeshes.ukx"
]);

export default assetList;
export { assetList };