const assetList = Object.freeze([
    "maps/17_22.unr",
    "maps/20_19.unr",
    "maps/20_20.unr",
    "maps/20_21.unr",
    "maps/20_22.unr",
    "maps/21_19.unr",
    "maps/21_20.unr",
    "maps/21_21.unr",
    "maps/22_21.unr",
    "textures/T_17_22.utx",
    "textures/T_20_19.utx",
    "textures/T_20_20.utx",
    "textures/T_20_21.utx",
    "textures/T_20_22.utx",
    "textures/T_21_19.utx",
    "textures/T_21_20.utx",
    "textures/T_21_21.utx",
    "textures/T_22_21.utx",
    "textures/T_sland.utx",
    "textures/T_texture.utx",
    "textures/T_Gludio.utx",
    "textures/T_Dion.utx",
    "textures/T_oren.utx",
    "textures/L2DecoLayer.utx",
    "models/field_deco_S.usx",
    "textures/field_deco_T.utx",
]);

export default assetList;
export { assetList };